<?php 

/** Auto generated by discovering the listeners. Don't edit this file manually. */

return array (
  'Example\\App\\Events\\SampleEvent' => 
  array (
    0 => 'Example\\App\\Listeners\\SampleListener',
    1 => 'Example\\App\\Listeners\\AnotherListener',
  ),
);