<?php 

/** Auto generated by discovering the policies. Don't edit this file manually. */

return array (
  0 => 
  array (
    'model' => 'Example\\App\\Models\\Event',
    'policy' => 'Example\\App\\Policies\\EventPolicy',
  ),
);